baseURL = 'https://me.paulrossethings.com/'
languageCode = 'en-us'
title = 'Paul Rosset'
theme = "hugo-theme-codex"

[params]
  description = "You are in my world, my home page, my log book, and this is a way for me to log what I like about life. On this site, you will find technical writing, life writing, and projects I've done throughout my life."
  twitter = "https://twitter.com/RossetPaul"
  keywords = "paul rosset, logbook, homepage, blog, life, programming, coding"

[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "Home"
  url = "/"
  weight = 1

[[menu.main]]
    identifier = "life-writing"
    name = "Life Writing"
    title = "Life Writing"
    url = "/life-writing"
    weight = 2

[[menu.main]]
    identifier = "technical-writing"
    name = "Technical Writing"
    title = "Technical Writing"
    url = "/technical-writing"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"
    weight = 4

[[menu.main]]
    identifier = "epikent"
    name = "Epikent (French)"
    title = "Epikent (French)"
    url = "https://epikent.paulrossethings.com/"
    weight = 5

[[menu.main]]
    identifier = "qonto-refer"
    name = "We are hiring!"
    title = "We are hiring!"
    url = "https://refer.hellotrusty.io/kudytqi2pb/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true