baseURL = 'https://me.paulrossethings.com/'
languageCode = 'en-us'
title = 'Paul Rosset - Software engineer'
theme = "hugo-theme-codex"
googleAnalytics = "G-2RXTKBY54H"

[params]
  description = "Paul Rosset's Homepage - You are in my world, my home page, my log book, this is a way for me to log the different tech projects and professional descision that a human person could take during his life. On this site, you will find technical writing, life writing, and projects I've done throughout my life."
  twitter = "https://twitter.com/RossetPaul"
  keywords = "paul,rosset,paul rosset, logbook, homepage, blog, life, programming, coding"

[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "Home"
  url = "/"
  weight = 1

[[menu.main]]
    identifier = "technical-writing"
    name = "Technical Writing"
    title = "Technical Writing"
    url = "/technical-writing"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"
    weight = 3

[[menu.main]]
    identifier = "life-writing"
    name = "Life Writing"
    title = "Life Writing"
    url = "/life-writing"
    weight = 4

[[menu.main]]
    identifier = "epikent"
    name = "Epikent (French)"
    title = "Epikent (French)"
    url = "https://epikent.paulrossethings.com/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true